import type { InfoSection } from "../views/InfoPage";

export interface StaticPageContent {
  path: string;
  title: string;
  description: string;
  sections: InfoSection[];
}

export const staticPages: StaticPageContent[] = [
  {
    path: "/about",
    title: "About Us.",
    description:
      "Lean Switch is the complete toolkit for your next career move — from company research to tailored resumes, interview prep to offer tracking.",
    sections: [
      {
        heading: "What we do.",
        paragraphs: [
          "Lean Switch helps job seekers manage their entire job search in one place. Research companies before you apply, track every application through a kanban pipeline, tailor your resume with AI, schedule interviews, log feedback from every round, and get noticed on our bidding board.",
        ],
      },
      {
        heading: "The bidding board.",
        paragraphs: [
          "Our bidding board connects job seekers with opportunities. You can pay to put yourself on the board to get noticed by companies and recruiters.",
        ],
      },
      {
        heading: "Why we built it.",
        paragraphs: [
          "Switching jobs is a full-time job. We built Lean Switch to remove the busywork — the scattered spreadsheets, forgotten follow-ups, and one-size-fits-all resumes — so you can focus on landing the right role.",
        ],
      },
    ],
  },
  {
    path: "/contact",
    title: "Contact Us.",
    description:
      "Questions, feedback, or need help? Reach out and we'll get back to you as soon as we can.",
    sections: [
      {
        heading: "Customer support.",
        paragraphs: [
          "Email: sanchittanwar9762@gmail.com",
          "We aim to respond to all inquiries within 2 business days.",
        ],
      },
    ],
  },
  {
    path: "/pricing",
    title: "Pricing Details.",
    description:
      "Transparent pricing, no surprises. Here's exactly what Lean Switch costs.",
    sections: [
      {
        heading: "Free plan.",
        paragraphs: [
          "Everything you need to get started: company research, kanban job tracking, interview calendar, and community question bank — free forever.",
        ],
      },
      {
        heading: "AI-powered features.",
        paragraphs: [
          "AI-powered resume tailoring and company research use your own LLM provider API key. You only pay your provider's token costs — Lean Switch takes absolutely 0 cut.",
        ],
      },
      {
        heading: "Bidding board.",
        paragraphs: [
          "You can pay to put yourself on the bidding board to get noticed by companies and recruiters. All bidding board payments are non-refundable.",
        ],
      },
      {
        heading: "No hidden fees.",
        paragraphs: [
          "There are no subscription fees, setup costs, or cancellation charges. Any paid features are clearly labeled before you use them.",
        ],
      },
    ],
  },
  {
    path: "/terms",
    title: "Terms and Conditions.",
    description:
      "The rules for using Lean Switch and its services. Please read them carefully.",
    sections: [
      {
        heading: "Acceptance of terms.",
        paragraphs: [
          "By accessing or using Lean Switch, you agree to be bound by these Terms and Conditions. If you do not agree, do not use the service.",
        ],
      },
      {
        heading: "Use of the service.",
        paragraphs: [
          "You are responsible for the content you upload, including resumes and application data. You agree not to use the service for any unlawful purpose or to infringe the rights of others.",
        ],
      },
      {
        heading: "Bidding board payments.",
        paragraphs: [
          "You may pay to place yourself on the bidding board. All bidding board payments are non-refundable.",
        ],
      },
      {
        heading: "AI-generated content.",
        paragraphs: [
          "AI-tailored resumes and company research are generated by third-party language models using your own API key. You are responsible for reviewing all generated content for accuracy before relying on it.",
        ],
      },
      {
        heading: "Limitation of liability.",
        paragraphs: [
          "Lean Switch is provided on an 'as is' basis. To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
        ],
      },
    ],
  },
  {
    path: "/privacy",
    title: "Privacy Policy.",
    description:
      "How we collect, use, and protect your data. Your privacy matters to us.",
    sections: [
      {
        heading: "Data we collect.",
        paragraphs: [
          "We collect the information you provide when using the service, including your account details, resumes, job applications, and interview notes. We also collect basic usage data to improve the product.",
        ],
      },
      {
        heading: "How we use your data.",
        paragraphs: [
          "Your data is used solely to provide and improve the service. We do not sell your personal information to third parties.",
        ],
      },
      {
        heading: "How we protect your data.",
        paragraphs: [
          "Authentication is handled via Supabase with secure JWT sessions. Your files are stored in a private per-user workspace and are never shared publicly.",
        ],
      },
      {
        heading: "Account deletion.",
        paragraphs: [
          "Account deletion is not currently supported. To stop using the service, simply discontinue use. Contact support if you need help with your account.",
        ],
      },
      {
        heading: "Third-party services.",
        paragraphs: [
          "AI features use your own LLM provider credentials. Content sent to your provider is governed by that provider's own privacy policy.",
        ],
      },
    ],
  },
  {
    path: "/refund",
    title: "Refund / Cancellation Policy.",
    description:
      "Clear terms for refunds and cancellations. We keep it simple.",
    sections: [
      {
        heading: "Cancellation.",
        paragraphs: [
          "You can stop using Lean Switch at any time. There are no cancellation fees or lock-in periods. Account deletion is not currently supported.",
        ],
      },
      {
        heading: "Refunds.",
        paragraphs: [
          "All bidding board payments are non-refundable. AI-powered resume tailoring and company research are billed directly by your own LLM provider, so Lean Switch does not process those payments and cannot issue refunds on their behalf.",
        ],
      },
      {
        heading: "How to request support.",
        paragraphs: [
          "Email sanchittanwar9762@gmail.com with your account email and a description of the issue. We'll respond within 2 business days.",
        ],
      },
    ],
  },
];
